services:
  config_producer:
    build:
      dockerfile: Dockerfile
      target: config_producer
    container_name: config_producer_proto
    restart: no
    env_file: env-docker
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data:/data

