services:

  config_producer:
    build:
      dockerfile: Dockerfile
      target: config_producer
    container_name: config_producer_proto
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data:/data
      - ${PWD}/.env:/.env
    depends_on:
      - data_quality

  data_quality:
    build:
      dockerfile: Dockerfile
      target: data_quality
    container_name: data_quality_server
    restart: unless-stopped
    ports:
      - "${DATA_QUALITY_SERVER_PORT}:${DATA_QUALITY_SERVER_PORT}"
    environment:
      - RUST_LOG=debug
      - DATA_QUALITY_SERVER_IP
      - DATA_QUALITY_SERVER_PORT
    volumes:
      - ./data:/data
      - ${PWD}/.env:/.env

  load_test:
    build:
      dockerfile: Dockerfile
      target: load_test
    container_name: load_test_data_quality_server
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
      - DATA_QUALITY_SERVER_PORT
    volumes:
      - ${PWD}/.env:/.env






