services:
  config_producer:
    build:
      dockerfile: Dockerfile
      target: config_producer
    container_name: config_producer_proto
    restart: no
    env_file: env-docker
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data:/data
    depends_on:
      - data_quality

  data_quality:
    build:
      dockerfile: Dockerfile
      target: data_quality
    container_name: data_quality_server
    restart: unless-stopped
    env_file: env-docker
    ports:
      - "${DATA_QUALITY_SERVER_PORT}:${DATA_QUALITY_SERVER_PORT}"
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data:/data

  load_test:
    build:
      dockerfile: Dockerfile
      target: load_test
    restart: no
    env_file: env-docker
    environment:
      - RUST_LOG=debug
    depends_on:
      - config_producer