services:
  data_quality:
    build:
      dockerfile: Dockerfile
      target: data_quality
    container_name: data_quality_server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      - RUST_LOG=debug
      - SERVER_PORT
    volumes:
      - ./data:/data
      - ${PWD}/.env:/.env

  config_producer:
    build:
      dockerfile: Dockerfile
      target: config_producer
    container_name: config_producer_proto
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data:/data
      - ${PWD}/.env:/.env
    depends_on:
      - data_quality

