[package]
name = "dynamic-message"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { workspace = true }
prost-reflect = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }