# docker-compose.yml
version: '3'

services:
  load-test-wget:
    build:
      context: .
      args:
        - RUN_AMOUNT=${RUN_AMOUNT}
        - SERVER_IP=${SERVER_IP}
        - SERVER_PORT=${SERVER_PORT}
    environment:
      - RUN_AMOUNT=${RUN_AMOUNT}
      - SERVER_IP=${SERVER_IP}
      - SERVER_PORT=${SERVER_PORT}
    command: ["/load-test.sh", "--wget"]
    deploy:
      replicas: 2
    restart: "no"

  load-test-curl:
    build:
      context: .
      args:
        - RUN_AMOUNT=${RUN_AMOUNT}
        - SERVER_IP=${SERVER_IP}
        - SERVER_PORT=${SERVER_PORT}
    environment:
      - RUN_AMOUNT=${RUN_AMOUNT}
      - SERVER_IP=${SERVER_IP}
      - SERVER_PORT=${SERVER_PORT}
    command: ["/load-test.sh", "--curl"]
    deploy:
      replicas: 5
    restart: "no"
